"""Root + world positions + rot6d + local velocities + contact (266D).

Replace only HumanML3D's 63D RIC block with 66D world XYZ. Keep ALL other
raw features. Root origin is canonical as in HumanML3D. No learned codec.
"""
import sys
from pathlib import Path
import torch
from torch import nn
from .representation263 import CONTACT_JOINTS

sys.path.insert(0,str(Path(__file__).resolve().parents[1]/'third_party/FloodDiffusion'))
from utils.motion_process import recover_root_rot_pos
from utils.math.quaternion import qrot, qinv


def recover_xyz263(features):
    q,root=recover_root_rot_pos(features)
    relative=features[...,4:67].reshape(*features.shape[:-1],21,3)
    xyz=qrot(qinv(q)[...,None,:].expand(*q.shape[:-1],21,4),relative)
    translation=root.clone(); translation[...,1]=0
    xyz=xyz+translation[...,None,:]
    return torch.cat([root[...,None,:],xyz],-2)


def from263(features):
    if features.shape[-1]!=263: raise ValueError('expected HumanML3D 263D')
    return torch.cat([features[...,:4],recover_xyz263(features).flatten(-2),features[...,67:]],-1)


def xyz266(features):
    if features.shape[-1]!=266: raise ValueError('expected motion 266D')
    return features[...,4:70].reshape(*features.shape[:-1],22,3)


def to263(features):
    """Deterministic consistent evaluator export, without changing output XYZ.

    Root/local linear velocities are recomputed from explicit XYZ, except the
    final unavailable next-frame difference, which retains its predicted value.
    Rotations, angular velocity and contacts are retained, not regenerated by IK.
    Global initial XZ translation is removed only for the 263D evaluator.
    """
    xyz=xyz266(features)
    q,_=recover_root_rot_pos(features[...,:4])
    root=xyz[...,0,:]
    translation=root.clone(); translation[...,1]=0
    relative=qrot(q[...,None,:].expand(*q.shape[:-1],21,4),xyz[...,1:,:]-translation[...,None,:])
    delta=xyz[...,1:,:,:]-xyz[...,:-1,:,:]
    root_vel=qrot(q[...,1:,:],delta[...,0,:])[...,[0,2]]
    local_vel=qrot(q[...,:-1,None,:].expand(*delta.shape[:-1],4),delta).flatten(-2)
    root_vel=torch.cat([root_vel,features[...,-1:,1:3]],-2)
    local_vel=torch.cat([local_vel,features[...,-1:,196:262]],-2)
    root_block=torch.cat([features[...,:1],root_vel,root[...,1:2]],-1)
    return torch.cat([root_block,relative.flatten(-2),features[...,70:196],local_vel,features[...,262:266]],-1)


GROUPS266=[list(range(4))+list(range(4,7))+list(range(196,199))]
for j in range(1,22):
    GROUPS266.append(list(range(4+3*j,7+3*j))+list(range(70+6*(j-1),70+6*j))+list(range(196+3*j,199+3*j)))
for k,j in enumerate(CONTACT_JOINTS): GROUPS266[j].append(262+k)
assert sorted(c for g in GROUPS266 for c in g)==list(range(266))


class Layout266(nn.Module):
    def __init__(self):
        super().__init__()
        index=torch.zeros(22,13,dtype=torch.long); live=torch.zeros(22,13,dtype=torch.bool)
        reverse=torch.empty(266,dtype=torch.long); owner=torch.empty(266,dtype=torch.long)
        for j,g in enumerate(GROUPS266):
            index[j,:len(g)]=torch.tensor(g); live[j,:len(g)]=True
            for k,c in enumerate(g): reverse[c]=j*13+k; owner[c]=j
        self.register_buffer('index',index); self.register_buffer('live',live)
        self.register_buffer('reverse',reverse); self.register_buffer('owner',owner)
    def pack(self,x):
        if x.shape[-1]!=266: raise ValueError('expected 266D')
        return x[...,self.index]*self.live.to(x.dtype)
    def unpack(self,x): return x.flatten(-2)[...,self.reverse]


def position_mask(joints):
    if joints.dtype!=torch.bool or joints.shape[-1]!=22: raise ValueError('expected boolean joint mask')
    known=torch.zeros(*joints.shape[:-1],266,dtype=torch.bool,device=joints.device)
    known[...,4:70]=joints[...,None].expand(*joints.shape,3).flatten(-2)
    return known


class Normalizer266(nn.Module):
    def __init__(self,mean,std):
        super().__init__()
        mean=torch.as_tensor(mean).float(); std=torch.as_tensor(std).float()
        if mean.shape!=(266,) or std.shape!=(266,) or not torch.isfinite(mean).all() or not torch.isfinite(std).all() or (std<=0).any(): raise ValueError('invalid normalization')
        self.register_buffer('mean',mean); self.register_buffer('std',std)
    def normalize(self,x): return (x-self.mean)/self.std
    def denormalize(self,x): return x*self.std+self.mean


def fit_overfit_normalizer(clips,official_mean,official_std):
    """Reuse all 200 unchanged channel stats; fit only world XYZ on TRAIN clips.

    Overfit-only statistics are diagnostic, not approved for full benchmark use.
    """
    pos=torch.cat([from263(x)[...,4:70] for x in clips],0)
    mean=torch.cat([official_mean[:4],pos.mean(0),official_mean[67:]])
    std=torch.cat([official_std[:4],pos.std(0,unbiased=False).clamp_min(.05),official_std[67:]])
    return Normalizer266(mean,std)


def redundancy_loss(raw,valid):
    exported=to263(raw)
    # Self-consistency independent of GT; root height, root linear velocity,
    # and local joint velocity. Rotation/position consistency is diagnosed
    # separately and is not falsely guaranteed by this loss.
    residual=torch.cat([raw[...,1:4]-exported[...,1:4],raw[...,196:262]-exported[...,193:259]],-1)
    pair=valid[...,:-1]&valid[...,1:]
    return residual[...,:-1,:].square().mean(-1)[pair].mean()
